import lamp from "@/assets/p-lamp.jpg";
import kitchen from "@/assets/p-kitchen.jpg";
import storage from "@/assets/p-storage.jpg";
import chair from "@/assets/p-chair.jpg";
import office from "@/assets/p-office.jpg";
import decor from "@/assets/p-decor.jpg";
import gift from "@/assets/p-gift.jpg";
import type { AdminState } from "./types";

const now = new Date("2026-08-10T10:00:00+05:30");

function daysAgo(n: number, hour = 10) {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  d.setHours(hour, 15, 0, 0);
  return d.toISOString();
}

export const ADMIN_SEED: AdminState = {
  categories: [
    { _id: "cat_lighting", name: "Lighting", slug: "lighting", createdAt: daysAgo(120) },
    { _id: "cat_kitchen", name: "Kitchen", slug: "kitchen", createdAt: daysAgo(120) },
    { _id: "cat_storage", name: "Storage", slug: "storage", createdAt: daysAgo(120) },
    { _id: "cat_furniture", name: "Furniture", slug: "furniture", createdAt: daysAgo(120) },
    { _id: "cat_office", name: "Office", slug: "office", createdAt: daysAgo(120) },
    { _id: "cat_decor", name: "Home Decor", slug: "decor", createdAt: daysAgo(120) },
    { _id: "cat_gifts", name: "Gifts", slug: "gifts", createdAt: daysAgo(120) },
  ],
  collections: [
    {
      _id: "col_new",
      name: "New Arrivals",
      slug: "new-arrivals",
      productIds: ["prod_nara", "prod_mira"],
      createdAt: daysAgo(60),
    },
    {
      _id: "col_best",
      name: "Best Sellers",
      slug: "best-sellers",
      productIds: ["prod_hoshi", "prod_ola", "prod_hana"],
      createdAt: daysAgo(60),
    },
    {
      _id: "col_eco",
      name: "Eco Collection",
      slug: "eco-collection",
      productIds: ["prod_hoshi", "prod_sumi", "prod_ola"],
      createdAt: daysAgo(45),
    },
    {
      _id: "col_premium",
      name: "Premium Bamboo Collection",
      slug: "premium-bamboo",
      productIds: ["prod_kaze", "prod_hoshi"],
      createdAt: daysAgo(30),
    },
  ],
  products: [
    {
      _id: "prod_hoshi",
      name: "Hoshi Woven Pendant Lamp",
      description:
        "Hand-coiled bamboo shade that scatters light like dappled forest sun. Each shade is coiled from a single split culm.",
      categoryId: "cat_lighting",
      collectionIds: ["col_best", "col_eco", "col_premium"],
      price: 14999,
      discountPrice: 12999,
      sku: "BH-LAMP-001",
      images: [lamp],
      stock: 12,
      lowStockThreshold: 5,
      material: "Natural Bamboo",
      dimensions: "Ø 42 cm × H 34 cm",
      weight: "1.2 kg",
      color: "Honey",
      ecoFriendly: true,
      craftType: "handwoven",
      careInstructions: "Dust with a dry brush. Keep away from prolonged damp.",
      status: "active",
      createdAt: daysAgo(90),
      updatedAt: daysAgo(2),
    },
    {
      _id: "prod_nara",
      name: "Nara Serving Board Set",
      description: "Three graduated boards pressed from laminated bamboo.",
      categoryId: "cat_kitchen",
      collectionIds: ["col_new"],
      price: 2499,
      sku: "BH-KIT-002",
      images: [kitchen],
      stock: 34,
      lowStockThreshold: 8,
      material: "Laminated Bamboo",
      dimensions: "38 / 30 / 22 cm long",
      weight: "0.9 kg",
      color: "Natural",
      ecoFriendly: true,
      craftType: "handmade",
      careInstructions: "Hand wash, dry upright, re-oil monthly.",
      status: "active",
      createdAt: daysAgo(70),
      updatedAt: daysAgo(5),
    },
    {
      _id: "prod_ola",
      name: "Ola Lidded Storage Basket",
      description: "A generous woven vessel with a soft, sculpted lid.",
      categoryId: "cat_storage",
      collectionIds: ["col_best", "col_eco"],
      price: 3499,
      discountPrice: 2999,
      sku: "BH-STR-003",
      images: [storage],
      stock: 4,
      lowStockThreshold: 6,
      material: "Natural Bamboo",
      dimensions: "Ø 40 cm × H 45 cm",
      weight: "1.8 kg",
      color: "Warm Beige",
      ecoFriendly: true,
      craftType: "handwoven",
      careInstructions: "Vacuum gently. Spot clean with a damp cloth.",
      status: "active",
      createdAt: daysAgo(85),
      updatedAt: daysAgo(1),
    },
    {
      _id: "prod_kaze",
      name: "Kaze Bent Bamboo Lounge Chair",
      description: "Steam-bent frame with a hand-knotted seat that flexes as you sit.",
      categoryId: "cat_furniture",
      collectionIds: ["col_premium"],
      price: 45999,
      discountPrice: 41999,
      sku: "BH-FUR-004",
      images: [chair],
      stock: 3,
      lowStockThreshold: 4,
      material: "Steam-bent Bamboo",
      dimensions: "W 72 × D 80 × H 78 cm",
      weight: "8.5 kg",
      color: "Natural",
      ecoFriendly: true,
      craftType: "handmade",
      careInstructions: "Indoor use. Wipe with a soft dry cloth.",
      status: "active",
      createdAt: daysAgo(100),
      updatedAt: daysAgo(3),
    },
    {
      _id: "prod_sumi",
      name: "Sumi Desk Organiser",
      description: "Quiet compartments for a desk that thinks clearly.",
      categoryId: "cat_office",
      collectionIds: ["col_eco"],
      price: 1899,
      sku: "BH-OFF-005",
      images: [office],
      stock: 42,
      lowStockThreshold: 10,
      material: "Bamboo Off-cuts",
      dimensions: "W 28 × D 16 × H 11 cm",
      weight: "0.4 kg",
      color: "Light Natural",
      ecoFriendly: true,
      craftType: "machine-finished",
      careInstructions: "Dry dust only.",
      status: "active",
      createdAt: daysAgo(55),
      updatedAt: daysAgo(8),
    },
    {
      _id: "prod_mira",
      name: "Mira Woven Wall Panel",
      description: "A textured panel that turns a bare wall into a warm one.",
      categoryId: "cat_decor",
      collectionIds: ["col_new"],
      price: 4999,
      sku: "BH-DEC-006",
      images: [decor],
      stock: 0,
      lowStockThreshold: 5,
      material: "Natural Bamboo Fibre",
      dimensions: "W 60 × H 78 cm",
      weight: "1.1 kg",
      color: "Undyed",
      ecoFriendly: true,
      craftType: "handwoven",
      careInstructions: "Dust with a soft brush.",
      status: "active",
      createdAt: daysAgo(40),
      updatedAt: daysAgo(0, 9),
    },
    {
      _id: "prod_hana",
      name: "Hana Artisan Gift Box",
      description: "Our four most-loved small pieces, wrapped in bamboo paper.",
      categoryId: "cat_gifts",
      collectionIds: ["col_best"],
      price: 3499,
      discountPrice: 2999,
      sku: "BH-GFT-007",
      images: [gift],
      stock: 27,
      lowStockThreshold: 8,
      material: "Mixed Bamboo",
      dimensions: "W 32 × D 22 × H 12 cm",
      weight: "1.5 kg",
      color: "Assorted",
      ecoFriendly: true,
      craftType: "handmade",
      careInstructions: "See each enclosed piece.",
      status: "active",
      createdAt: daysAgo(65),
      updatedAt: daysAgo(4),
    },
    {
      _id: "prod_yumi",
      name: "Yumi Table Lamp",
      description: "A small companion light with a tapered woven shade.",
      categoryId: "cat_lighting",
      collectionIds: [],
      price: 8999,
      sku: "BH-LAMP-008",
      images: [lamp],
      stock: 5,
      lowStockThreshold: 6,
      material: "Natural Bamboo",
      dimensions: "Ø 24 cm × H 40 cm",
      weight: "0.8 kg",
      color: "Warm Honey",
      ecoFriendly: true,
      craftType: "handwoven",
      careInstructions: "Dust with a dry brush.",
      status: "active",
      createdAt: daysAgo(50),
      updatedAt: daysAgo(6),
    },
  ],
  customers: [
    {
      _id: "cust_anitha",
      name: "Anitha Krishnan",
      email: "anitha.k@email.com",
      phone: "+91 98765 43210",
      status: "active",
      joinedAt: daysAgo(200),
      addresses: [
        {
          id: "addr1",
          label: "Home",
          line1: "12 Lotus Lane, Adyar",
          city: "Chennai",
          state: "Tamil Nadu",
          pincode: "600020",
        },
      ],
      wishlistProductIds: ["prod_hoshi", "prod_kaze"],
    },
    {
      _id: "cust_rahul",
      name: "Rahul Mehta",
      email: "rahul.m@email.com",
      phone: "+91 98123 45678",
      status: "active",
      joinedAt: daysAgo(150),
      addresses: [
        {
          id: "addr2",
          label: "Home",
          line1: "88 Palm Grove, Bandra West",
          city: "Mumbai",
          state: "Maharashtra",
          pincode: "400050",
        },
      ],
      wishlistProductIds: ["prod_ola"],
    },
    {
      _id: "cust_vinitha",
      name: "Vinitha Rao",
      email: "vinitha.r@email.com",
      phone: "+91 99887 66554",
      status: "active",
      joinedAt: daysAgo(90),
      addresses: [
        {
          id: "addr3",
          label: "Office",
          line1: "Floor 4, Indiranagar Tech Park",
          city: "Bengaluru",
          state: "Karnataka",
          pincode: "560038",
        },
      ],
      wishlistProductIds: [],
    },
    {
      _id: "cust_arjun",
      name: "Arjun Patel",
      email: "arjun.p@email.com",
      phone: "+91 97654 32109",
      status: "active",
      joinedAt: daysAgo(45),
      addresses: [
        {
          id: "addr4",
          label: "Home",
          line1: "5 River View Apartments",
          city: "Ahmedabad",
          state: "Gujarat",
          pincode: "380015",
        },
      ],
      wishlistProductIds: ["prod_nara", "prod_hana"],
    },
    {
      _id: "cust_meera",
      name: "Meera Nair",
      email: "meera.n@email.com",
      phone: "+91 91234 56780",
      status: "inactive",
      joinedAt: daysAgo(300),
      addresses: [],
      wishlistProductIds: [],
    },
  ],
  orders: [
    {
      _id: "ord_1024",
      orderId: "BH1024",
      customerId: "cust_anitha",
      customerName: "Anitha Krishnan",
      customerEmail: "anitha.k@email.com",
      customerPhone: "+91 98765 43210",
      items: [
        { productId: "prod_hoshi", name: "Hoshi Woven Pendant Lamp", quantity: 1, price: 12999, image: lamp },
        { productId: "prod_sumi", name: "Sumi Desk Organiser", quantity: 1, price: 1899, image: office },
      ],
      subtotal: 14898,
      discount: 0,
      shipping: 0,
      tax: 2682,
      total: 17580,
      paymentStatus: "paid",
      paymentMethod: "upi",
      orderStatus: "delivered",
      shippingAddress: {
        line1: "12 Lotus Lane, Adyar",
        city: "Chennai",
        state: "Tamil Nadu",
        pincode: "600020",
      },
      timeline: [
        { label: "Order placed", at: daysAgo(12, 9), done: true },
        { label: "Payment received", at: daysAgo(12, 9), done: true },
        { label: "Processing", at: daysAgo(11, 11), done: true },
        { label: "Shipped", at: daysAgo(9, 14), done: true },
        { label: "Delivered", at: daysAgo(6, 16), done: true },
      ],
      createdAt: daysAgo(12, 9),
      updatedAt: daysAgo(6, 16),
    },
    {
      _id: "ord_1025",
      orderId: "BH1025",
      customerId: "cust_rahul",
      customerName: "Rahul Mehta",
      customerEmail: "rahul.m@email.com",
      customerPhone: "+91 98123 45678",
      items: [
        { productId: "prod_ola", name: "Ola Lidded Storage Basket", quantity: 1, price: 2999, image: storage },
        { productId: "prod_hana", name: "Hana Artisan Gift Box", quantity: 1, price: 2999, image: gift },
      ],
      subtotal: 5998,
      discount: 200,
      shipping: 99,
      tax: 1060,
      total: 6957,
      paymentStatus: "paid",
      paymentMethod: "razorpay",
      orderStatus: "processing",
      shippingAddress: {
        line1: "88 Palm Grove, Bandra West",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400050",
      },
      timeline: [
        { label: "Order placed", at: daysAgo(2, 11), done: true },
        { label: "Payment received", at: daysAgo(2, 11), done: true },
        { label: "Processing", at: daysAgo(1, 10), done: true },
        { label: "Shipped", at: "", done: false },
        { label: "Delivered", at: "", done: false },
      ],
      createdAt: daysAgo(2, 11),
      updatedAt: daysAgo(1, 10),
    },
    {
      _id: "ord_1026",
      orderId: "BH1026",
      customerId: "cust_vinitha",
      customerName: "Vinitha Rao",
      customerEmail: "vinitha.r@email.com",
      customerPhone: "+91 99887 66554",
      items: [
        { productId: "prod_kaze", name: "Kaze Bent Bamboo Lounge Chair", quantity: 1, price: 41999, image: chair },
      ],
      subtotal: 41999,
      discount: 0,
      shipping: 0,
      tax: 7560,
      total: 49559,
      paymentStatus: "paid",
      paymentMethod: "card",
      orderStatus: "new",
      shippingAddress: {
        line1: "Floor 4, Indiranagar Tech Park",
        city: "Bengaluru",
        state: "Karnataka",
        pincode: "560038",
      },
      timeline: [
        { label: "Order placed", at: daysAgo(0, 8), done: true },
        { label: "Payment received", at: daysAgo(0, 8), done: true },
        { label: "Processing", at: "", done: false },
        { label: "Shipped", at: "", done: false },
        { label: "Delivered", at: "", done: false },
      ],
      createdAt: daysAgo(0, 8),
      updatedAt: daysAgo(0, 8),
    },
    {
      _id: "ord_1027",
      orderId: "BH1027",
      customerId: "cust_arjun",
      customerName: "Arjun Patel",
      customerEmail: "arjun.p@email.com",
      customerPhone: "+91 97654 32109",
      items: [
        { productId: "prod_nara", name: "Nara Serving Board Set", quantity: 2, price: 2499, image: kitchen },
        { productId: "prod_yumi", name: "Yumi Table Lamp", quantity: 1, price: 8999, image: lamp },
      ],
      subtotal: 13997,
      discount: 500,
      shipping: 0,
      tax: 2429,
      total: 15926,
      paymentStatus: "pending",
      paymentMethod: "cod",
      orderStatus: "new",
      shippingAddress: {
        line1: "5 River View Apartments",
        city: "Ahmedabad",
        state: "Gujarat",
        pincode: "380015",
      },
      timeline: [
        { label: "Order placed", at: daysAgo(0, 14), done: true },
        { label: "Payment received", at: "", done: false },
        { label: "Processing", at: "", done: false },
        { label: "Shipped", at: "", done: false },
        { label: "Delivered", at: "", done: false },
      ],
      createdAt: daysAgo(0, 14),
      updatedAt: daysAgo(0, 14),
    },
    {
      _id: "ord_1028",
      orderId: "BH1028",
      customerId: "cust_rahul",
      customerName: "Rahul Mehta",
      customerEmail: "rahul.m@email.com",
      customerPhone: "+91 98123 45678",
      items: [
        { productId: "prod_mira", name: "Mira Woven Wall Panel", quantity: 1, price: 4999, image: decor },
      ],
      subtotal: 4999,
      discount: 0,
      shipping: 99,
      tax: 900,
      total: 5998,
      paymentStatus: "failed",
      paymentMethod: "netbanking",
      orderStatus: "cancelled",
      shippingAddress: {
        line1: "88 Palm Grove, Bandra West",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400050",
      },
      timeline: [
        { label: "Order placed", at: daysAgo(4, 13), done: true },
        { label: "Payment failed", at: daysAgo(4, 13), done: true },
        { label: "Cancelled", at: daysAgo(4, 14), done: true },
      ],
      createdAt: daysAgo(4, 13),
      updatedAt: daysAgo(4, 14),
    },
    {
      _id: "ord_1019",
      orderId: "BH1019",
      customerId: "cust_meera",
      customerName: "Meera Nair",
      customerEmail: "meera.n@email.com",
      customerPhone: "+91 91234 56780",
      items: [
        { productId: "prod_sumi", name: "Sumi Desk Organiser", quantity: 1, price: 1899, image: office },
      ],
      subtotal: 1899,
      discount: 0,
      shipping: 99,
      tax: 342,
      total: 2340,
      paymentStatus: "refunded",
      paymentMethod: "upi",
      orderStatus: "deleted",
      shippingAddress: {
        line1: "Old address",
        city: "Kochi",
        state: "Kerala",
        pincode: "682001",
      },
      timeline: [
        { label: "Order placed", at: daysAgo(40, 10), done: true },
        { label: "Cancelled & refunded", at: daysAgo(38, 12), done: true },
        { label: "Moved to recycle bin", at: daysAgo(37, 9), done: true },
      ],
      createdAt: daysAgo(40, 10),
      updatedAt: daysAgo(37, 9),
    },
    {
      _id: "ord_1020",
      orderId: "BH1020",
      customerId: "cust_anitha",
      customerName: "Anitha Krishnan",
      customerEmail: "anitha.k@email.com",
      customerPhone: "+91 98765 43210",
      items: [
        { productId: "prod_yumi", name: "Yumi Table Lamp", quantity: 1, price: 8999, image: lamp },
      ],
      subtotal: 8999,
      discount: 0,
      shipping: 0,
      tax: 1620,
      total: 10619,
      paymentStatus: "paid",
      paymentMethod: "razorpay",
      orderStatus: "shipped",
      shippingAddress: {
        line1: "12 Lotus Lane, Adyar",
        city: "Chennai",
        state: "Tamil Nadu",
        pincode: "600020",
      },
      timeline: [
        { label: "Order placed", at: daysAgo(7, 10), done: true },
        { label: "Payment received", at: daysAgo(7, 10), done: true },
        { label: "Processing", at: daysAgo(6, 11), done: true },
        { label: "Shipped", at: daysAgo(5, 15), done: true },
        { label: "Delivered", at: "", done: false },
      ],
      createdAt: daysAgo(7, 10),
      updatedAt: daysAgo(5, 15),
    },
  ],
  payments: [
    {
      _id: "pay_1",
      transactionId: "txn_rzp_8f2a1c",
      orderId: "ord_1024",
      orderRef: "BH1024",
      customerId: "cust_anitha",
      customerName: "Anitha Krishnan",
      amount: 17580,
      method: "upi",
      status: "paid",
      createdAt: daysAgo(12, 9),
    },
    {
      _id: "pay_2",
      transactionId: "txn_rzp_3b9e44",
      orderId: "ord_1025",
      orderRef: "BH1025",
      customerId: "cust_rahul",
      customerName: "Rahul Mehta",
      amount: 6957,
      method: "razorpay",
      status: "paid",
      createdAt: daysAgo(2, 11),
    },
    {
      _id: "pay_3",
      transactionId: "txn_card_77aa01",
      orderId: "ord_1026",
      orderRef: "BH1026",
      customerId: "cust_vinitha",
      customerName: "Vinitha Rao",
      amount: 49559,
      method: "card",
      status: "paid",
      createdAt: daysAgo(0, 8),
    },
    {
      _id: "pay_4",
      transactionId: "txn_cod_1027",
      orderId: "ord_1027",
      orderRef: "BH1027",
      customerId: "cust_arjun",
      customerName: "Arjun Patel",
      amount: 15926,
      method: "cod",
      status: "pending",
      createdAt: daysAgo(0, 14),
    },
    {
      _id: "pay_5",
      transactionId: "txn_nb_failed_9",
      orderId: "ord_1028",
      orderRef: "BH1028",
      customerId: "cust_rahul",
      customerName: "Rahul Mehta",
      amount: 5998,
      method: "netbanking",
      status: "failed",
      createdAt: daysAgo(4, 13),
    },
    {
      _id: "pay_6",
      transactionId: "txn_ref_1019",
      orderId: "ord_1019",
      orderRef: "BH1019",
      customerId: "cust_meera",
      customerName: "Meera Nair",
      amount: 2340,
      method: "upi",
      status: "refunded",
      createdAt: daysAgo(38, 12),
    },
    {
      _id: "pay_7",
      transactionId: "txn_rzp_1020",
      orderId: "ord_1020",
      orderRef: "BH1020",
      customerId: "cust_anitha",
      customerName: "Anitha Krishnan",
      amount: 10619,
      method: "razorpay",
      status: "paid",
      createdAt: daysAgo(7, 10),
    },
  ],
  settings: {
    store: {
      name: "The Handicraft House",
      email: "hello@handicrafthouse.com",
      phone: "+91 80 4567 8901",
      address: "Artisan Lane, Bengaluru, Karnataka 560001",
      currency: "INR",
    },
    admin: {
      name: "Store Admin",
      email: "admin@handicrafthouse.com",
    },
    shipping: {
      freeAbove: 2999,
      flatRate: 99,
      estimatedDays: "5–9 business days",
    },
    payment: {
      razorpayEnabled: true,
      upiEnabled: true,
      codEnabled: true,
    },
    notifications: {
      newOrderEmail: true,
      lowStockEmail: true,
      paymentFailedEmail: true,
    },
  },
};
